<template>
  <div class="list" ref="wrapper">
    <div class="content">
      <div class="area">
        <div class="title border-topbottom">当前城市</div>
        <div class="button-list">
          <div class="button-wraper">
            <div class="button">北京</div>
          </div>
        </div>
      </div>
      <div class="area">
        <div class="title border-topbottom">热门城市</div>
        <div class="button-list">
          <div class="button-wraper" v-for="(item, index) in cities" :key="index">
            <div class="button">{{item}}</div>
          </div>
        </div>
      </div>
      <div class="area">
        <div class="title border-topbottom">A</div>
        <div class="item-list" v-for="item of A" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">B</div>
        <div class="item-list" v-for="item of B" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">C</div>
        <div class="item-list" v-for="item of C" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">D</div>
        <div class="item-list" v-for="item of D" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">E</div>
        <div class="item-list" v-for="item of E" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">F</div>
        <div class="item-list" v-for="item of F" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">G</div>
        <div class="item-list" v-for="item of G" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
        <div class="title border-topbottom">H</div>
        <div class="item-list" v-for="item of H" :key="item.id">
          <div class="item border-bottom">{{item.name}}</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import BScroll from '@better-scroll/core';
import Pullup from '@better-scroll/pull-up';

BScroll.use(Pullup);

export default {
  name: 'CityList',
  data() {
    return {
      cities: ['北京', '上海', '广州', '深圳', '南京', '杭州', '武汉', '西安'],
      scroll: null,
      A: [{
        id: 56,
        spell: 'aba',
        name: '阿坝',
      }, {
        id: 57,
        spell: 'akesu',
        name: '阿克苏',
      }, {
        id: 58,
        spell: 'alashanmeng',
        name: '阿拉善盟',
      }, {
        id: 59,
        spell: 'aletai',
        name: '阿勒泰',
      }, {
        id: 60,
        spell: 'ali',
        name: '阿里',
      }, {
        id: 61,
        spell: 'ankang',
        name: '安康',
      }, {
        id: 62,
        spell: 'anqing',
        name: '安庆',
      }, {
        id: 63,
        spell: 'anshan',
        name: '鞍山',
      }, {
        id: 64,
        spell: 'anshun',
        name: '安顺',
      }, {
        id: 65,
        spell: 'anyang',
        name: '安阳',
      }, {
        id: 338,
        spell: 'acheng',
        name: '阿城',
      }, {
        id: 339,
        spell: 'anfu',
        name: '安福',
      }, {
        id: 340,
        spell: 'anji',
        name: '安吉',
      }, {
        id: 341,
        spell: 'anning',
        name: '安宁',
      }, {
        id: 342,
        spell: 'anqiu',
        name: '安丘',
      }, {
        id: 343,
        spell: 'anxi',
        name: '安溪',
      }, {
        id: 344,
        spell: 'anyi',
        name: '安义',
      }, {
        id: 345,
        spell: 'anyuan',
        name: '安远',
      }],
      B: [{
        id: 1,
        spell: 'beijing',
        name: '北京',
      }, {
        id: 66,
        spell: 'baicheng',
        name: '白城',
      }, {
        id: 67,
        spell: 'baise',
        name: '百色',
      }, {
        id: 68,
        spell: 'baishan',
        name: '白山',
      }, {
        id: 69,
        spell: 'baiyin',
        name: '白银',
      }, {
        id: 70,
        spell: 'bangbu',
        name: '蚌埠',
      }, {
        id: 71,
        spell: 'baoding',
        name: '保定',
      }, {
        id: 72,
        spell: 'baoji',
        name: '宝鸡',
      }, {
        id: 73,
        spell: 'baoshan',
        name: '保山',
      }, {
        id: 74,
        spell: 'baotou',
        name: '包头',
      }, {
        id: 75,
        spell: 'bayannaoer',
        name: '巴彦淖尔',
      }, {
        id: 76,
        spell: 'bayinguoleng',
        name: '巴音郭楞',
      }, {
        id: 77,
        spell: 'bazhong',
        name: '巴中',
      }, {
        id: 78,
        spell: 'beihai',
        name: '北海',
      }, {
        id: 79,
        spell: 'benxi',
        name: '本溪',
      }, {
        id: 80,
        spell: 'bijie',
        name: '毕节',
      }, {
        id: 81,
        spell: 'binzhou',
        name: '滨州',
      }, {
        id: 82,
        spell: 'boertala',
        name: '博尔塔拉',
      }, {
        id: 83,
        spell: 'bozhou',
        name: '亳州',
      }, {
        id: 346,
        spell: 'baoying',
        name: '宝应',
      }, {
        id: 347,
        spell: 'bayan',
        name: '巴彦',
      }, {
        id: 348,
        spell: 'binhai',
        name: '滨海',
      }, {
        id: 349,
        spell: 'binxian',
        name: '宾县',
      }, {
        id: 350,
        spell: 'binyang',
        name: '宾阳',
      }, {
        id: 351,
        spell: 'bishan',
        name: '璧山',
      }, {
        id: 352,
        spell: 'boai',
        name: '博爱',
      }, {
        id: 353,
        spell: 'boluo',
        name: '博罗',
      }, {
        id: 354,
        spell: 'boxing',
        name: '博兴',
      }],
      C: [{
        id: 2,
        spell: 'chongqing',
        name: '重庆',
      }, {
        id: 5,
        spell: 'changchun',
        name: '长春',
      }, {
        id: 6,
        spell: 'changsha',
        name: '长沙',
      }, {
        id: 7,
        spell: 'changzhou',
        name: '常州',
      }, {
        id: 8,
        spell: 'chengdu',
        name: '成都',
      }, {
        id: 84,
        spell: 'cangzhou',
        name: '沧州',
      }, {
        id: 85,
        spell: 'changde',
        name: '常德',
      }, {
        id: 86,
        spell: 'changdu',
        name: '昌都',
      }, {
        id: 87,
        spell: 'changji',
        name: '昌吉',
      }, {
        id: 88,
        spell: 'changzhi',
        name: '长治',
      }, {
        id: 89,
        spell: 'chaohu',
        name: '巢湖',
      }, {
        id: 90,
        spell: 'chaoyang',
        name: '朝阳',
      }, {
        id: 91,
        spell: 'chaozhou',
        name: '潮州',
      }, {
        id: 92,
        spell: 'chengde',
        name: '承德',
      }, {
        id: 93,
        spell: 'chenzhou',
        name: '郴州',
      }, {
        id: 94,
        spell: 'chifeng',
        name: '赤峰',
      }, {
        id: 95,
        spell: 'chizhou',
        name: '池州',
      }, {
        id: 96,
        spell: 'chongzuo',
        name: '崇左',
      }, {
        id: 97,
        spell: 'chuxiong',
        name: '楚雄',
      }, {
        id: 98,
        spell: 'chuzhou',
        name: '滁州',
      }, {
        id: 355,
        spell: 'cangnan',
        name: '苍南',
      }, {
        id: 356,
        spell: 'cangshan',
        name: '苍山',
      }, {
        id: 357,
        spell: 'caoxian',
        name: '曹县',
      }, {
        id: 358,
        spell: 'changdao',
        name: '长岛',
      }, {
        id: 359,
        spell: 'changfeng',
        name: '长丰',
      }, {
        id: 360,
        spell: 'changhai',
        name: '长海',
      }, {
        id: 361,
        spell: 'changle',
        name: '长乐',
      }, {
        id: 362,
        spell: 'changle',
        name: '昌乐',
      }, {
        id: 363,
        spell: 'changshan',
        name: '常山',
      }, {
        id: 364,
        spell: 'changshu',
        name: '常熟',
      }, {
        id: 365,
        spell: 'changtai',
        name: '长泰',
      }, {
        id: 366,
        spell: 'changting',
        name: '长汀',
      }, {
        id: 367,
        spell: 'changxing',
        name: '长兴',
      }, {
        id: 368,
        spell: 'changyi',
        name: '昌邑',
      }, {
        id: 369,
        spell: 'chaoan',
        name: '潮安',
      }, {
        id: 370,
        spell: 'chenggong',
        name: '呈贡',
      }, {
        id: 371,
        spell: 'chengkou',
        name: '城口',
      }, {
        id: 372,
        spell: 'chengwu',
        name: '成武',
      }, {
        id: 373,
        spell: 'chiping',
        name: '茌平',
      }, {
        id: 374,
        spell: 'chongren',
        name: '崇仁',
      }, {
        id: 375,
        spell: 'chongyi',
        name: '崇义',
      }, {
        id: 376,
        spell: 'chongzhou',
        name: '崇州',
      }, {
        id: 377,
        spell: 'chunan',
        name: '淳安',
      }, {
        id: 378,
        spell: 'cixi',
        name: '慈溪',
      }, {
        id: 379,
        spell: 'conghua',
        name: '从化',
      }, {
        id: 380,
        spell: 'congyang',
        name: '枞阳',
      }],
      D: [{
        id: 9,
        spell: 'dalian',
        name: '大连',
      }, {
        id: 10,
        spell: 'dongguan',
        name: '东莞',
      }, {
        id: 99,
        spell: 'dali',
        name: '大理',
      }, {
        id: 100,
        spell: 'dandong',
        name: '丹东',
      }, {
        id: 101,
        spell: 'daqing',
        name: '大庆',
      }, {
        id: 102,
        spell: 'datong',
        name: '大同',
      }, {
        id: 103,
        spell: 'daxinganling',
        name: '大兴安岭',
      }, {
        id: 104,
        spell: 'dazhou',
        name: '达州',
      }, {
        id: 105,
        spell: 'dehong',
        name: '德宏',
      }, {
        id: 106,
        spell: 'deyang',
        name: '德阳',
      }, {
        id: 107,
        spell: 'dezhou',
        name: '德州',
      }, {
        id: 108,
        spell: 'dingxi',
        name: '定西',
      }, {
        id: 109,
        spell: 'diqing',
        name: '迪庆',
      }, {
        id: 110,
        spell: 'dongying',
        name: '东营',
      }, {
        id: 381,
        spell: 'dafeng',
        name: '大丰',
      }, {
        id: 382,
        spell: 'daishan',
        name: '岱山',
      }, {
        id: 383,
        spell: 'dangshan',
        name: '砀山',
      }, {
        id: 384,
        spell: 'dangtu',
        name: '当涂',
      }, {
        id: 385,
        spell: 'danxian',
        name: '单县',
      }, {
        id: 386,
        spell: 'danyang',
        name: '丹阳',
      }, {
        id: 387,
        spell: 'dapu',
        name: '大埔',
      }, {
        id: 388,
        spell: 'datian',
        name: '大田',
      }, {
        id: 389,
        spell: 'dayi',
        name: '大邑',
      }, {
        id: 390,
        spell: 'dayu',
        name: '大余',
      }, {
        id: 391,
        spell: 'dazu',
        name: '大足',
      }, {
        id: 392,
        spell: 'dean',
        name: '德安',
      }, {
        id: 393,
        spell: 'dehua',
        name: '德化',
      }, {
        id: 394,
        spell: 'dehui',
        name: '德惠',
      }, {
        id: 395,
        spell: 'dengfeng',
        name: '登封',
      }, {
        id: 396,
        spell: 'deqing',
        name: '德清',
      }, {
        id: 397,
        spell: 'deqing',
        name: '德庆',
      }, {
        id: 398,
        spell: 'dexing',
        name: '德兴',
      }, {
        id: 399,
        spell: 'dianbai',
        name: '电白',
      }, {
        id: 400,
        spell: 'dianjiang',
        name: '垫江',
      }, {
        id: 401,
        spell: 'dingnan',
        name: '定南',
      }, {
        id: 402,
        spell: 'dingtao',
        name: '定陶',
      }, {
        id: 403,
        spell: 'dingyuan',
        name: '定远',
      }, {
        id: 404,
        spell: 'donga',
        name: '东阿',
      }, {
        id: 405,
        spell: 'donghai',
        name: '东海',
      }, {
        id: 406,
        spell: 'dongming',
        name: '东明',
      }, {
        id: 407,
        spell: 'dongping',
        name: '东平',
      }, {
        id: 408,
        spell: 'dongshan',
        name: '东山',
      }, {
        id: 409,
        spell: 'dongtai',
        name: '东台',
      }, {
        id: 410,
        spell: 'dongtou',
        name: '洞头',
      }, {
        id: 411,
        spell: 'dongxiang',
        name: '东乡',
      }, {
        id: 412,
        spell: 'dongyang',
        name: '东阳',
      }, {
        id: 413,
        spell: 'dongyuan',
        name: '东源',
      }, {
        id: 414,
        spell: 'dongzhi',
        name: '东至',
      }, {
        id: 415,
        spell: 'duchang',
        name: '都昌',
      }, {
        id: 416,
        spell: 'dujiangyan',
        name: '都江堰',
      }],
      E: [{
        id: 111,
        spell: 'eerduosi',
        name: '鄂尔多斯',
      }, {
        id: 112,
        spell: 'enshi',
        name: '恩施',
      }, {
        id: 113,
        spell: 'ezhou',
        name: '鄂州',
      }, {
        id: 417,
        spell: 'enping',
        name: '恩平',
      }],
      F: [{
        id: 11,
        spell: 'foshan',
        name: '佛山',
      }, {
        id: 12,
        spell: 'fuzhou',
        name: '福州',
      }, {
        id: 114,
        spell: 'fangchenggang',
        name: '防城港',
      }, {
        id: 115,
        spell: 'fushun',
        name: '抚顺',
      }, {
        id: 116,
        spell: 'fuxin',
        name: '阜新',
      }, {
        id: 117,
        spell: 'fuyang',
        name: '阜阳',
      }, {
        id: 118,
        spell: 'fuzhou',
        name: '抚州',
      }, {
        id: 418,
        spell: 'faku',
        name: '法库',
      }, {
        id: 419,
        spell: 'fanchang',
        name: '繁昌',
      }, {
        id: 420,
        spell: 'fangzheng',
        name: '方正',
      }, {
        id: 421,
        spell: 'feicheng',
        name: '肥城',
      }, {
        id: 422,
        spell: 'feidong',
        name: '肥东',
      }, {
        id: 423,
        spell: 'feixi',
        name: '肥西',
      }, {
        id: 424,
        spell: 'feixian',
        name: '费县',
      }, {
        id: 425,
        spell: 'fengcheng',
        name: '丰城',
      }, {
        id: 426,
        spell: 'fengdu',
        name: '丰都',
      }, {
        id: 427,
        spell: 'fenghua',
        name: '奉化',
      }, {
        id: 428,
        spell: 'fengjie',
        name: '奉节',
      }, {
        id: 429,
        spell: 'fengkai',
        name: '封开',
      }, {
        id: 430,
        spell: 'fengshun',
        name: '丰顺',
      }, {
        id: 431,
        spell: 'fengtai',
        name: '凤台',
      }, {
        id: 432,
        spell: 'fengxian',
        name: '丰县',
      }, {
        id: 433,
        spell: 'fengxin',
        name: '奉新',
      }, {
        id: 434,
        spell: 'fengyang',
        name: '凤阳',
      }, {
        id: 435,
        spell: 'fenyi',
        name: '分宜',
      }, {
        id: 436,
        spell: 'fogang',
        name: '佛冈',
      }, {
        id: 437,
        spell: 'fuan',
        name: '福安',
      }, {
        id: 438,
        spell: 'fuding',
        name: '福鼎',
      }, {
        id: 439,
        spell: 'fuliang',
        name: '浮梁',
      }, {
        id: 440,
        spell: 'fumin',
        name: '富民',
      }, {
        id: 441,
        spell: 'funan',
        name: '阜南',
      }, {
        id: 442,
        spell: 'funing',
        name: '阜宁',
      }, {
        id: 443,
        spell: 'fuqing',
        name: '福清',
      }, {
        id: 444,
        spell: 'fuyang',
        name: '富阳',
      }],
      G: [{
        id: 13,
        spell: 'guangzhou',
        name: '广州',
      }, {
        id: 14,
        spell: 'guiyang',
        name: '贵阳',
      }, {
        id: 119,
        spell: 'gannan',
        name: '甘南',
      }, {
        id: 120,
        spell: 'ganzhou',
        name: '赣州',
      }, {
        id: 121,
        spell: 'ganzi',
        name: '甘孜',
      }, {
        id: 122,
        spell: 'guangan',
        name: '广安',
      }, {
        id: 123,
        spell: 'guangyuan',
        name: '广元',
      }, {
        id: 124,
        spell: 'guigang',
        name: '贵港',
      }, {
        id: 125,
        spell: 'guilin',
        name: '桂林',
      }, {
        id: 126,
        spell: 'guoluo',
        name: '果洛',
      }, {
        id: 127,
        spell: 'guyuan',
        name: '固原',
      }, {
        id: 445,
        spell: 'ganxian',
        name: '赣县',
      }, {
        id: 446,
        spell: 'ganyu',
        name: '赣榆',
      }, {
        id: 447,
        spell: 'gaoan',
        name: '高安',
      }, {
        id: 448,
        spell: 'gaocheng',
        name: '藁城',
      }, {
        id: 449,
        spell: 'gaochun',
        name: '高淳',
      }, {
        id: 450,
        spell: 'gaolan',
        name: '皋兰',
      }, {
        id: 451,
        spell: 'gaoling',
        name: '高陵',
      }, {
        id: 452,
        spell: 'gaomi',
        name: '高密',
      }, {
        id: 453,
        spell: 'gaoqing',
        name: '高青',
      }, {
        id: 454,
        spell: 'gaotang',
        name: '高唐',
      }, {
        id: 455,
        spell: 'gaoyao',
        name: '高要',
      }, {
        id: 456,
        spell: 'gaoyi',
        name: '高邑',
      }, {
        id: 457,
        spell: 'gaoyou',
        name: '高邮',
      }, {
        id: 458,
        spell: 'gaozhou',
        name: '高州',
      }, {
        id: 459,
        spell: 'gongyi',
        name: '巩义',
      }, {
        id: 460,
        spell: 'guangchang',
        name: '广昌',
      }, {
        id: 461,
        spell: 'guangde',
        name: '广德',
      }, {
        id: 462,
        spell: 'guangfeng',
        name: '广丰',
      }, {
        id: 463,
        spell: 'guangning',
        name: '广宁',
      }, {
        id: 464,
        spell: 'guangrao',
        name: '广饶',
      }, {
        id: 465,
        spell: 'guangze',
        name: '光泽',
      }, {
        id: 466,
        spell: 'guannan',
        name: '灌南',
      }, {
        id: 467,
        spell: 'guanxian',
        name: '冠县',
      }, {
        id: 468,
        spell: 'guanyun',
        name: '灌云',
      }, {
        id: 469,
        spell: 'guixi',
        name: '贵溪',
      }, {
        id: 470,
        spell: 'gutian',
        name: '古田',
      }, {
        id: 471,
        spell: 'guzhen',
        name: '固镇',
      }],
      H: [{
        id: 15,
        spell: 'haerbin',
        name: '哈尔滨',
      }, {
        id: 16,
        spell: 'haikou',
        name: '海口',
      }, {
        id: 17,
        spell: 'handan',
        name: '邯郸',
      }, {
        id: 18,
        spell: 'hangzhou',
        name: '杭州',
      }, {
        id: 19,
        spell: 'hefei',
        name: '合肥',
      }, {
        id: 20,
        spell: 'huizhou',
        name: '惠州',
      }, {
        id: 128,
        spell: 'haibei',
        name: '海北',
      }, {
        id: 129,
        spell: 'haidong',
        name: '海东',
      }, {
        id: 130,
        spell: 'hainan',
        name: '海南',
      }, {
        id: 131,
        spell: 'haixi',
        name: '海西',
      }, {
        id: 132,
        spell: 'hami',
        name: '哈密',
      }, {
        id: 133,
        spell: 'hanzhong',
        name: '汉中',
      }, {
        id: 134,
        spell: 'hebi',
        name: '鹤壁',
      }, {
        id: 135,
        spell: 'hechi',
        name: '河池',
      }, {
        id: 136,
        spell: 'hegang',
        name: '鹤岗',
      }, {
        id: 137,
        spell: 'heihe',
        name: '黑河',
      }, {
        id: 138,
        spell: 'hengshui',
        name: '衡水',
      }, {
        id: 139,
        spell: 'hengyang',
        name: '衡阳',
      }, {
        id: 140,
        spell: 'hetiandi',
        name: '和田地',
      }, {
        id: 141,
        spell: 'heyuan',
        name: '河源',
      }, {
        id: 142,
        spell: 'heze',
        name: '菏泽',
      }, {
        id: 143,
        spell: 'hezhou',
        name: '贺州',
      }, {
        id: 144,
        spell: 'honghe',
        name: '红河',
      }, {
        id: 145,
        spell: 'huaian',
        name: '淮安',
      }, {
        id: 146,
        spell: 'huaibei',
        name: '淮北',
      }, {
        id: 147,
        spell: 'huaihua',
        name: '怀化',
      }, {
        id: 148,
        spell: 'huainan',
        name: '淮南',
      }, {
        id: 149,
        spell: 'huanggang',
        name: '黄冈',
      }, {
        id: 150,
        spell: 'huangnan',
        name: '黄南',
      }, {
        id: 151,
        spell: 'huangshan',
        name: '黄山',
      }, {
        id: 152,
        spell: 'huangshi',
        name: '黄石',
      }, {
        id: 153,
        spell: 'huhehaote',
        name: '呼和浩特',
      }, {
        id: 154,
        spell: 'huludao',
        name: '葫芦岛',
      }, {
        id: 155,
        spell: 'hulunbeier',
        name: '呼伦贝尔',
      }, {
        id: 156,
        spell: 'huzhou',
        name: '湖州',
      }, {
        id: 472,
        spell: 'haian',
        name: '海安',
      }, {
        id: 473,
        spell: 'haifeng',
        name: '海丰',
      }, {
        id: 474,
        spell: 'haimen',
        name: '海门',
      }, {
        id: 475,
        spell: 'haining',
        name: '海宁',
      }, {
        id: 476,
        spell: 'haiyan',
        name: '海盐',
      }, {
        id: 477,
        spell: 'haiyang',
        name: '海阳',
      }, {
        id: 478,
        spell: 'hanshan',
        name: '含山',
      }, {
        id: 479,
        spell: 'hechuan',
        name: '合川',
      }, {
        id: 480,
        spell: 'hengfeng',
        name: '横峰',
      }, {
        id: 481,
        spell: 'hengxian',
        name: '横县',
      }, {
        id: 482,
        spell: 'heping',
        name: '和平',
      }, {
        id: 483,
        spell: 'heshan',
        name: '鹤山',
      }, {
        id: 484,
        spell: 'hexian',
        name: '和县',
      }, {
        id: 485,
        spell: 'hongze',
        name: '洪泽',
      }, {
        id: 486,
        spell: 'huaan',
        name: '华安',
      }, {
        id: 487,
        spell: 'huadian',
        name: '桦甸',
      }, {
        id: 488,
        spell: 'huaiji',
        name: '怀集',
      }, {
        id: 489,
        spell: 'huaining',
        name: '怀宁',
      }, {
        id: 490,
        spell: 'huaiyuan',
        name: '怀远',
      }, {
        id: 491,
        spell: 'huantai',
        name: '桓台',
      }, {
        id: 492,
        spell: 'huazhou',
        name: '化州',
      }, {
        id: 493,
        spell: 'huian',
        name: '惠安',
      }, {
        id: 494,
        spell: 'huichang',
        name: '会昌',
      }, {
        id: 495,
        spell: 'huidong',
        name: '惠东',
      }, {
        id: 496,
        spell: 'huilai',
        name: '惠来',
      }, {
        id: 497,
        spell: 'huimin',
        name: '惠民',
      }, {
        id: 498,
        spell: 'hukou',
        name: '湖口',
      }, {
        id: 499,
        spell: 'hulan',
        name: '呼兰',
      }, {
        id: 500,
        spell: 'huoqiu',
        name: '霍邱',
      }, {
        id: 501,
        spell: 'huoshan',
        name: '霍山',
      }, {
        id: 502,
        spell: 'huxian',
        name: '户县',
      }],
    };
  },
  props: {
    letter: String,
  },
  mounted() {
    this.scroll = new BScroll(this.$refs.wrapper, {
      probeType: 3,
      click: true,
      pullUpLoad: true,
      useTransition: false,
    });
  },
  watch: {
    letter() {
      if (this.letter) {
        console.log(this.letter);
      }
    },
  },
};
</script>

<style lang="stylus" scoped>
.border-topbottom
  &:before
    border-color #ccc
  &:after
    border-color #ccc
.border-bottom
  &:before
    border-color #ccc
.list
  overflow hidden
  position absolute
  top 1.68rem
  bottom 0
  left 0
  right 0
  .title
    line-height .54rem
    background #eee
    padding-left .2rem
    color #666
    font-size 0.26rem
  .button-list
    padding 0.1rem 0.6rem 0.1rem 0.1rem
    overflow hidden
    .button-wraper
      float left
      width 33.33%
      .button
        margin 0.1rem
        text-align center
        border 0.02rem solid #ccc
        padding 0.1rem 0
        border-radius 0.06rem
.item-list
  line-height 0.76rem
  color #666
  padding-left 0.2rem
</style>
